FROM nginx:alpine

COPY nginx.conf /etc/nginx/nginx.conf

# Copy ALL static files (full folder!)
COPY foodtrucks/project/flask-app/static /usr/share/nginx/html/static

# Copy HTML template
COPY foodtrucks/project/flask-app/templates/index.html /usr/share/nginx/html/index.html
