FROM alpine:3.11
WORKDIR /app

# Copy all files
COPY foodtrucks/project/flask-app /app
COPY requirements.txt /app/requirements.txt
COPY foodtrucks/project/utils /app/utils

# Install ALL tools (build + runtime) in one stage
RUN apk add --no-cache nodejs npm python2 py2-pip && \
    pip2 install -r requirements.txt && \
    npm install && \
    npm run build

# Expose the port and run the app
EXPOSE 5000
ENTRYPOINT ["python2", "app.py"]